TRAITS = [
    {
        "rank": 1,
        "name": "Adrenaline",
        "icon": "img/Adrenaline.png",
        "cost": 1,
        "description": "Instantly start regenerating Stamina while your Health is critically low.",
    },
    {
        "rank": 1,
        "name": "Bloodless",
        "icon": "img/Bloodless.png",
        "cost": 4,
        "description": "Bleeding will not escalate from light to medium or intense bleeding. (i.e. any bleeding you incur will only ever be light bleeding).",
    },
    {
        "rank": 1,
        "name": "Conduit",
        "icon": "img/Conduit.png",
        "cost": 4,
        "description": "Get a health and stamina boost when picking up a Clue, Rift, or Bounty token.",
    },
    {
        "rank": 1,
        "name": "Greyhound",
        "icon": "img/Greyhound.png",
        "cost": 4,
        "description": "Sprint at full speed for a longer duration. (Roughly doubles the duration).",
    },
    {
        "rank": 1,
        "name": "Hornskin",
        "icon": "img/Hornskin.png",
        "cost": 3,
        "description": "Reduce damage taken from blunt melee by 25%.",
    },
    {
        "rank": 1,
        "name": "Magpie",
        "icon": "img/Magpie.png",
        "cost": 1,
        "description": "Receive a short effect similiar to that of either the Antidote Shot, Stamina Shot or Regeneration Shot, when picking up a Bounty Token.",
    },
    {
        "rank": 1,
        "name": "Packmule",
        "icon": "img/Packmule.png",
        "cost": 3,
        "description": "Receive an additional tool or consumable when looting players or opening item boxes.",
    },
    {
        "rank": 1,
        "name": "Salveskin",
        "icon": "img/Salveskin.png",
        "cost": 5,
        "description": "Reduces fire damage and burn speed by 25%, even when downed.",
    },
    {
        "rank": 5,
        "name": "Determination",
        "icon": "img/Determination.png",
        "cost": 3,
        "description": "Stamina recovery starts sooner. (Applies to both melee and sprinting stamina).",
    },
    {
        "rank": 7,
        "name": "Iron Repeater",
        "icon": "img/Iron_Repeater.png",
        "cost": 2,
        "description": "Remain in iron sights after firing a shot while using lever-action rifles. (Applies to all scope-less Winfield lever-action variants, including shotguns).",
    },
    {
        "rank": 9,
        "name": "Resilience",
        "icon": "img/Resilience.png",
        "cost": 2,
        "description": "Get revived with up to 100 Health.",
    },
    {
        "rank": 11,
        "name": "Assailant",
        "icon": "img/Assailant.png",
        "cost": 2,
        "description": "Increases melee damage of throwing knives and throwing axes.",
    },
    {
        "rank": 13,
        "name": "Bolt Thrower",
        "icon": "img/Bolt_Thrower.png",
        "cost": 3,
        "description": "Reduced reload time for crossbows.",
    },
    {
        "rank": 14,
        "name": "Levering",
        "icon": "img/Levering.png",
        "cost": 3,
        "description": "Faster rate of fire from the hip when using lever-action weapons. (Applies to all Winfield lever-action variants, including shotguns).",
    },
    {
        "rank": 15,
        "name": "Mithridatist",
        "icon": "img/Mithridatist.png",
        "cost": 3,
        "description": "Drastically reduces the time needed to recover from poisoning.",
    },
    {
        "rank": 16,
        "name": "Bulwark",
        "icon": "img/Bulwark.png",
        "cost": 2,
        "description": "Reduce the damage from explosions and Bomb Lance harpoon attacks by 50%.",
    },
    {
        "rank": 17,
        "name": "Fanning",
        "icon": "img/Fanning.png",
        "cost": 7,
        "description": "Faster rate-of-fire when using 1-handed single-action pistols.",
    },
    {
        "rank": 19,
        "name": "Ghoul",
        "icon": "img/Ghoul.png",
        "cost": 4,
        "description": "Killing Grunts at close-range restores a small amount of health. (25m range, restores 5 health).",
    },
    {
        "rank": 21,
        "name": "Gator Legs",
        "icon": "img/Gator_Legs.png",
        "cost": 2,
        "description": "Walk and sprint faster in deep water. Also make less noise while crouched in water.",
    },
    {
        "rank": 23,
        "name": "Deadeye Scopesmith",
        "icon": "img/Deadeye_Scopesmith.png",
        "cost": 1,
        "description": "Remain in scope view after firing a shot while using any weapon with a short scope (Deadeye variants).",
    },
    {
        "rank": 25,
        "name": "Silent Killer",
        "icon": "img/Silent_Killer.png",
        "cost": 5,
        "description": "Reduces the sound you make when performing melee attacks.",
    },
    {
        "rank": 27,
        "name": "Lightfoot",
        "icon": "img/Lightfoot.png",
        "cost": 5,
        "description": "Vault, jump, fall, and climb ladders silently.",
    },
    {
        "rank": 28,
        "name": "Serpent",
        "icon": "img/Serpent.png",
        "cost": 4,
        "description": "Using Dark Sight, interact with nearby Clues, Rifts, Banishable Targets, and abandoned Bounty from a safe distance. (25m range).",
    },
    {
        "rank": 29,
        "name": "Physician",
        "icon": "img/Physician.png",
        "cost": 5,
        "description": "Reduce the time needed to bandage. (With the First Aid Kit).",
    },
    {
        "rank": 31,
        "name": "Steady Aim",
        "icon": "img/Steady_Aim.png",
        "cost": 3,
        "description": "Weapon sway gradually lessens when you're looking through the scope of a rifle. (Applies to any 3-slot rifle with a scope or aperture sight).",
    },
    {
        "rank": 33,
        "name": "Steady Hand",
        "icon": "img/Steady_Hand.png",
        "cost": 2,
        "description": "Weapon sway gradually lessens when you're looking through the scope of a pistol or a stock-less weapon. (Applies to 2-slot weapons with a scope).",
    },
    {
        "rank": 35,
        "name": "Marksman Scopesmith",
        "icon": "img/Marksman_Scopesmith.png",
        "cost": 2,
        "description": "Remain in scope view after firing a shot while using any weapon with a medium scope (Marksman variants).",
    },
    {
        "rank": 38,
        "name": "Vigor",
        "icon": "img/Vigor.png",
        "cost": 4,
        "description": "While in Dark Sight, doubles the rate at which Health and Stamina regenerate.",
    },
    {
        "rank": 38,
        "name": "Whispersmith",
        "icon": "img/Whispersmith.png",
        "cost": 2,
        "description": "Reduces noise when selecting equipment.",
    },
    {
        "rank": 39,
        "name": "Frontiersman",
        "icon": "img/Frontiersman.png",
        "cost": 8,
        "description": "Carried tools can be used one extra time.",
    },
    {
        "rank": 41,
        "name": "Beastface",
        "icon": "img/Beastface.png",
        "cost": 3,
        "description": "Reduced reaction range of animals (doesn't affect monsters like Hellhounds).",
    },
    {
        "rank": 43,
        "name": "Decoy Supply",
        "icon": "img/Decoy_Supply.png",
        "cost": 1,
        "description": "Restock all types of decoys from ammo crates.",
    },
    {
        "rank": 44,
        "name": "Ambidextrous",
        "icon": "img/Ambidextrous.png",
        "cost": 3,
        "description": "Quicker reloading of matched pairs, and custom clip reloads for semi-auto pistol sets.",
    },
    {
        "rank": 45,
        "name": "Tomahawk",
        "icon": "img/Tomahawk.png",
        "cost": 1,
        "description": "Melee weapons found in the world can be thrown.",
    },
    {
        "rank": 47,
        "name": "Iron Sharpshooter",
        "icon": "img/Iron_Sharpshooter.png",
        "cost": 3,
        "description": "Remain in iron sights after firing a shot while using bolt-action rifles. (Applies to all scope-less bolt-action rifles, including Vetterli, Berthier, Lebel, and Mosin variants, excluding the Mosin Avtomat).",
    },
    {
        "rank": 49,
        "name": "Blade Seer",
        "icon": "img/Blade_Seer.png",
        "cost": 2,
        "description": "Bolts, arrows, throwing axes, and throwing knives are highlighted in Dark Sight for better visibility. (25m range, line of sight required).",
    },
    {
        "rank": 51,
        "name": "Quartermaster",
        "icon": "img/Quartermaster.png",
        "cost": 6,
        "description": "Can equip a medium slot weapon in addition to a large slot weapon.",
    },
    {
        "rank": 55,
        "name": "Pitcher",
        "icon": "img/Pitcher.png",
        "cost": 6,
        "description": "Increased throwing range for all items using the aim helper. (Roughly 50% increased range).",
    },
    {
        "rank": 57,
        "name": "Bulletgrubber",
        "icon": "img/Bulletgrubber.png",
        "cost": 6,
        "description": "Recover the unfired round when performing partial reloads. (Applies to Bornheim, Dolch, Lebel, Mosin, Berthier, Specter, and Terminus variants).",
    },
    {
        "rank": 59,
        "name": "Poacher",
        "icon": "img/Poacher.png",
        "cost": 1,
        "description": "Place and disarm traps quietly.",
    },
    {
        "rank": 60,
        "name": "Hundred Hands",
        "icon": "img/Hundred_Hands.png",
        "cost": 3,
        "description": "Increases the damage of a Hunting Bow shot at full draw by 10%. Also reduces sway whilst at full draw.",
    },
    {
        "rank": 61,
        "name": "Dauntless",
        "icon": "img/Dauntless.png",
        "cost": 1,
        "description": "Thrown explosives can be defused when interacting with them (3m interaction range).",
    },
    {
        "rank": 63,
        "name": "Kiteskin",
        "icon": "img/Kiteskin.png",
        "cost": 1,
        "description": "Reduce damage from falling by 50%.",
    },
    {
        "rank": 65,
        "name": "Iron Devastator",
        "icon": "img/Iron_Devastator.png",
        "cost": 2,
        "description": "Remain in iron sights between shots using pump-action shotguns. (Applies to Winfield Slate and Specter 1882 variants).",
    },
    {
        "rank": 67,
        "name": "Dewclaw",
        "icon": "img/Dewclaw.png",
        "cost": 2,
        "description": "Enhances the melee attack of a bow and arrow.",
    },
    {
        "rank": 69,
        "name": "Necromancer",
        "icon": "img/Necromancer.png",
        "cost": 4,
        "description": "Using Dark Sight, revive a downed partner from a distance, though at the cost of a small amount of health. (25m range, costs 25 Health).",
    },
    {
        "rank": 71,
        "name": "Vulture",
        "icon": "img/Vulture.png",
        "cost": 3,
        "description": "Always be able to loot dead Hunters, even after they have been looted by other players.",
    },
    {
        "rank": 73,
        "name": "Doctor",
        "icon": "img/Doctor.png",
        "cost": 8,
        "description": "Doubles the amount of Health restored by First Aid Kits.",
    },
    {
        "rank": 77,
        "name": "Sniper Scopesmith",
        "icon": "img/Sniper_Scopesmith.png",
        "cost": 3,
        "description": "Remain in scope view after firing a shot while using any weapon with a long scope (Sniper variants).",
    },
    {
        "rank": 84,
        "name": "Poison Sense",
        "icon": "img/Poison_Sense.png",
        "cost": 1,
        "description": "You can see nearby poisoned Hunters while in Dark Sight. (50m range).",
    },
    {
        "rank": 87,
        "name": "Vigilant",
        "icon": "img/Vigilant.png",
        "cost": 2,
        "description": "Nearby traps are highlighted in Dark Sight. (25m range).",
    },
]

_name_to_trait = {trait["name"]: trait for trait in TRAITS}


def get_trait_by_name(name):
    return _name_to_trait.get(name)
